apiVersion: apps/v1
kind: Deployment
metadata:
  name: online-store-app-deployment
  labels:
    app: online-store
spec:
  replicas: 2
  selector:
    matchLabels:
      app: online-store
  template:
    metadata:
      labels:
        app: online-store
    spec:
      containers:
      - name: online-store-container
        image: prmd77/onlinestore
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: onlinestore-service
spec:
  selector:
    app: online-store
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 32040
