apiVersion: apps/v1
kind: Deployment
metadata:
  name: onlinestore-deployment
  labels:
    app: onlinestore
spec:
  replicas: 2
  selector:
    matchLabels:
      app: onlinestore
  template:
    metadata:
      labels:
        app: onlinestore
    spec:
      containers:
      - name: onlinestore
        image: your-dockerhub-username/onlinestore:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql-service:3306/onlinestore"
        - name: SPRING_DATASOURCE_USERNAME
          value: "root"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "password"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: onlinestore-service
spec:
  selector:
    app: onlinestore
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
  nodePort: 32040  # Exposed port on the node
